import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const mont = localFont({
    src: [
        { path: "./fonts/Mont-HeavyDEMO.otf", weight: "800" },
        { path: "./fonts/Mont-ExtraLightDEMO.otf", weight: "200" },
    ],
    variable: "--font-mont",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                geistSans.variable,
                geistMono.variable,
                mont.variable,
                "font-sans",
                inter.variable,
            )}
        >
            <body className="min-h-full overflow-hidden flex flex-col">
                <Navbar></Navbar>
                {children}
            </body>
        </html>
    );
}
